name: Persistent Pterodactyl VPS with Auto Backup

on:
  workflow_dispatch:
  schedule:
    - cron: "*/3 * * * *" # Har 3 min me backup

jobs:
  run-vps:
    runs-on: ubuntu-latest
    steps:
      - name: Install & Start VPS
        run: |
          sudo apt update && sudo apt install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virt-manager cloud-utils wget
          wget https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img -O vps.img
          qemu-system-x86_64 -m 2048 -smp 2 -hda vps.img -net nic -net user,hostfwd=tcp::2222-:22 &

      - name: Wait for VPS to boot
        run: sleep 60

      - name: Install Pterodactyl & Cloudflared inside VPS
        run: |
          sshpass -p 'root' ssh -o StrictHostKeyChecking=no -p 2222 root@127.0.0.1 "
          apt update &&
          bash <(curl -s https://pterodactyl-installer.se) &&
          apt install -y cloudflared &&
          cloudflared service install <TOKEN>"

      - name: Create backup folder
        run: mkdir -p backups

      - name: Take backup
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          sshpass -p 'root' ssh -o StrictHostKeyChecking=no -p 2222 root@127.0.0.1 "
          tar -czf /tmp/ptero_backup_$TIMESTAMP.tar.gz /var/www/pterodactyl /etc/cloudflared"
          scp -P 2222 root@127.0.0.1:/tmp/ptero_backup_$TIMESTAMP.tar.gz backups/

      - name: Delete old backup if new one exists
        run: |
          if [ $(ls backups | wc -l) -gt 1 ]; then
            ls -t backups | tail -n +2 | xargs -I {} rm backups/{}
          fi

      - name: Send backup to second VPS every 6 hours
        if: ${{ github.event.schedule == '0 */6 * * *' }}
        run: |
          LATEST_BACKUP=$(ls -t backups | head -n 1)
          scp backups/$LATEST_BACKUP user@SECOND_VPS:/path/to/store
